### PR TITLE
Fix Crash on Kodi v20.0 (Nexus)

### PR DESCRIPTION
**Pull request by Kalacione**
Inspired by @camelreef "typical shit" commit
From https://github.com/melmorabity/plugin.video.francetv/pull/5/commits/923672b1bca68397d16f3c8cf7a0b8957e88dd6e

### CODE REVIEW

**Comment by myurkoski** [comment]
This gets everything working perfectly with V20.0.

**Comment by jonas2k** [comment]
Confirmed! Works flawlessly again...

**Comment by teeedubb** [comment]
@Kalacione thank you very much for the fix.
Also thanks to @myurkoski and @jonas2k for testing.

**Comment by Kalacione** [comment]
Thank you all folks, you make the Internet a better place.

**Pull request merged**
