### PR TITLE
Fix for Windows

### PR DESCRIPTION
**Pull request by smvicente**
The script wasn't working for me with those "titles" in the groups.

### CODE REVIEW

**Comment by smvicente** [comment]
If fine, I can also create another PR with the new compiled binary. But I guess maybe you prefer to compile it yourself?

**Comment by teeedubb** [comment]
Hi,

Are you able to post screenshots of the output of Window Spy when running steam in desktop mode and BPM? And were you having issues with BPM or DM?
I have looked into the window string, and while I saw that the steam desktop mode window has changed, the string for BPM matches what is present in the script and should work fine.
DM:
image

BPM:
image

**Comment by smvicente** [comment]
While doing this I just realized what the problem was... the BMP title is in Spanish!
bpm
steam

Before it wasn't like that I think. In any case, removing the title seems to work fine in every case?

Best.

**Comment by smvicente** [comment]
Ok now I see DM changed indeed, so it is same class as BPM but with different tittle...

**Comment by teeedubb** [comment]
Thats interesting, different names in other languages was something I was not aware of. 
I dont want to remove addittional checks for window titles as the script uses the differences to detect changing to desktop mode and steam updates, plus any other issues it could introduce.
For now youll need to manuall edit the steam-launcher.ahk script and compile it.
I'll see if its possible to add alternate window title filters via the addon settings.

**Comment by smvicente** [comment]
Sure! I didn't realize about that either because with previous BPM UI was same title in all languages. So I tink we can close the PR then :)

**Comment by teeedubb** [comment]
Can you test 3.7.9 and report back?
It has an advanced setting to set custom window titles
[script.steam.launcher-3.7.9.zip](https://github.com/teeedubb/teeedubb-xbmc-repo/files/13317793/script.steam.launcher-3.7.9.zip)

**Comment by smvicente** [comment]
Hey this is perfect and I can confirm it's working fine on my side!

Thank you for taking the time to add this.

**Pull request closed without merging**
