### PR TITLE
Adding pt-br translation to steam launcher

### PR DESCRIPTION
**Pull request by rokam**
Adding pt-br translation to steam launcher

### CODE REVIEW

**Comment by RobLoach** [comment]
:+1:

**Comment by rokam** [comment]
@teeedubb can you merge it?

**Comment by teeedubb** [comment]
Hi,

I don’t know how I missed this, I'm really sorry about it taking so long.
Thanks for the contribution, it has been merged and a I'll publish a new version tomorrow when I have access to a PC.

Sorry again and thanks.

**Comment by rokam** [comment]
I've added an update PR to add a new translation that was missing: #7

**Pull request merged**
